### POST "Hello!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Hello!"
}

### POST "Bonjour!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Bonjour!"
}

### POST "Privet!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Privet!"
}

### GET all messages
GET http://localhost:8080/

### GET specific message
GET http://localhost:8080/061af181-832a-4956-b662-7885b11ca76c

### DELETE specific messsage
DELETE http://localhost:8080/29cfc69f-3b7d-4060-8fb6-847172e38611

### PATCH specific message
PATCH http://localhost:8080/061af181-832a-4956-b662-7885b11ca76c
Content-Type: application/json

{
  "text": "tomale"
}